.rubocop.yml, README.md, lib/alba.rb, lib/alba/resource.rb, test/usecases/on_error_test.rb
This feature lets users to decide how to deal with errors that occurred when fetching an attribute.
It's especially useful when the serialized object is connected to the database or the network that might causes some errors.
=> Implement user defined error handling

alba.gemspec
Hi, I find the broken URL for the changelog in <https://rubygems.org/gems/alba/versions/1.0.0>:
This PR just fixes it. Thanks. 😃
=> Fix changelog URL in gemspec

benchmark/local.rb
Hey, I like your simple gem and that it includes a benchmark with various other gems. I was missing the **jsonapi-serializers** (formerly known as _fast_jsonapi_) gem and therefore I've added it.  I've also added `benchmark/ips` and refactored the benchmark file (sorting calls and declarations alphabetically and adding some comments to make it simpler to understand the file).
Ok, now you might wonder: _"but jsonapi-serializers formats the output differently"_ and you would be correct. But as I've done in a few projects before, where some endpoints needed a simple, 'flat' serialization and didn't follow the JSON:API standard, I've overwritten its `as_json` method to get the same output as with the other serializers.
And it is still fast, almost as fast as **alba**.
---
> _I recommend to …
=> Add jsonapi-serializer gem to benchmark and clean up the file

benchmark/local.rb
@mediafinger asked if I could push my branch where I added Primalize to the benchmark. Nice work making it so easy to extend!
Primalize is a type-checking serializer library, written while I was at a previous company to validate their API output. I wrote a [blog post](https://dev.to/jgaskins/fast-type-checked-serializers-for-ruby-web-apis-2o19) about the type-checking part of it, but we also discovered at the time that it was pretty fast, so I figured when I saw Alba in Ruby Weekly and there was a benchmark already written that I'd check it against Primalize. 🙂
=> Add primalize benchmark

lib/alba/resource.rb, test/usecases/key_transform_test.rb, test/usecases/with_inference_test.rb
At the moment, when serializing an object with a multiple-word name, the inferred key becomes a single word. For example: `BankAccount` => `bankaccount`.
```ruby
require 'alba'
Alba.enable_inference!
class BankAcccount
attr_accessor :account_number
def initialize(account_number:)
@account_number = account_number
end
end
class BankAccountResource
key!
attributes :account_number
end
bank_account = BankAcccount.new(account_number: 123456789)
puts BankAccountResource.new(bank_account).serialize
puts BankAccountResource.new([bank_account]).serialize
```
Output:
```ruby
{"bankaccount":{"account_number":123456789}}
{"bankaccounts":[{"account_number":123456789}]}
```
This PR replaces `String#downcase` by `ActiveSupport::Inflector.underscore` in `Alba::Resource::_key` …
=> [Fix] Fix multiple-word key inference

README.md, lib/alba.rb, lib/alba/resource.rb, test/usecases/key_transform_test.rb
And `root` option to `transform_keys` method.
This feature is an improvement over the previous commit,
6c18e731310183dc5ca6f626431987b4cdf685f8
It transforms root key, which is a great idea but introduces
backward incompatibility.
This commit adds the flag to control this transformation behavior,
which is default to the old behavior (not transforming root key).
cc: @alfonsojimenez
=> [Feat] Add `Alba.enable_root_key_transformation!`

lib/alba/many.rb, lib/alba/resource.rb
Running [benchmark](https://github.com/okuramasafumi/alba/blob/main/benchmark/collection.rb) shows a surprising result.
Before:
```
alba:       20.9 i/s
alba     3.720M memsize (    47.240k retained)
64.620k objects (   601.000  retained)
50.000  strings (     1.000  retained)
```
After:
```
alba:       27.4 i/s
alba     2.291M memsize (    47.240k retained)
39.920k objects (   601.000  retained)
50.000  strings (     1.000  retained)
```
Now it's 30% more performant and consumes 40% less memory!
=> [Perf] Improve performance for `many`

lib/alba.rb, lib/alba/resource.rb, test/alba_test.rb, test/resource_test.rb, test/usecases/circular_association_test.rb, test/usecases/collection_test.rb, test/usecases/key_transform_test.rb, test/usecases/no_association_test.rb, test/usecases/on_error_test.rb, test/usecases/params_test.rb, test/usecases/user_defined_serializable_hash_test.rb, test/usecases/with_inference_test.rb
- `Resource.root_key` and `Resource.root_key!`
- Ability to set key for collection via `root_key` second parameter
- `root_key` option to `Resource#serialize` and `Alba.serialize`
None
- Tests to use new `root_key` version
- `Resource.key` and `Resource.key!` are now deprecated
- `key` option for `Resource#serialize` and `Alba.serialize` are also deprecated
=> Improve key

docs/migrate_from_active_model_serializers.md
https://github.com/okuramasafumi/alba/issues/98
=> Add migration documents from ASM

benchmark/single_resource.rb
Hi!
I'm Panko author, I ran the benchmarks (thanks @jaydorsey for the PR) and saw that the output of `commenter_names` was `["name", "name"]`, looks like it was looking on the wrong association.
About the issue here - https://github.com/okuramasafumi/alba/pull/156#issuecomment-898986886, I'll investigate it and will make sure that `pg` won't be a required dependency.
=> benchmarks: fix commenter names in panko

lib/alba/resource.rb, test/usecases/with_struct_test.rb
`Struct` is `Enumerable`, so Alba misunderstood that it's a collection.
Now Alba checks if it's NOT a `Struct` for being a collection.
=> [Fix] Alba now works with Struct

README.md
I understand that this was added to maintain the documentation, but it doesn't seem to be working correctly.
I did some research and it seems that the PR needs to be created and merged according to the following rules.
http://inch-pages.github.io/participate/?github
However, it is unclear whether the above maintenance will continue or not, so I have removed it. Please consider it.
It may be better for the owner to send it, but If you request me to do so, I can send PR to the above repo. In that case, please feel free to close this PR.
=> [Doc] Remove a badge for Inch-CI

lib/alba/association.rb, lib/alba/many.rb, lib/alba/one.rb, lib/alba/resource.rb, test/deprecation_test.rb, test/usecases/nil_handler_test.rb, test/usecases/no_association_test.rb
`to_hash` is a special method that Ruby interpreter invokes when
the object should be treated as Hash.
For example, when we call methods having keyword arguments with
hash using double splat(`**`).
```ruby
method_with_kwargs(**object) # => object.to_hash is invoked
```
When `Alba::Resource` object's `to_hash` is called, it doesn't work.
To resolve this problem `to_hash` method must be deprecated.
`serializable_hash` is now aliased to `to_h`, that's OK.
=> [Deprecate] `to_hash` is special method and should not be used

README.md
I ran the example code and received different result.
That's because the code specified `root_key`.
=> Fix the result of example code in README

README.md, lib/alba/resource.rb, test/usecases/inheritance_and_ignorance_test.rb, test/usecases/nested_array_and_hash_test.rb
Using `ignoring` deletes (not filters) attributes, that might
consequence some problems.
Now we can do filtering safely by overriding `attributes` method.
=> [Deprecate] `ignoring` in favor of `attributes` overriding

lib/alba/association.rb, lib/alba/resource.rb, lib/alba/typed_attribute.rb
Seems Object#send has the better performance then Object#public_send.
- Kubuntu 21.10
- AMD Ryzen 7 5700G
- gcc version 11.2.0
- Ruby 3.1.1
```
Warming up --------------------------------------
Object#send     1.443M i/100ms
Object#public_send     1.239M i/100ms
Calculating -------------------------------------
Object#send     14.514M (± 1.9%) i/s -     73.585M in   5.071831s
Object#public_send     12.476M (± 0.4%) i/s -     63.214M in   5.066893s
Comparison:
Object#send: 14514416.9 i/s
Object#public_send: 12476119.8 i/s - 1.16x  (± 0.00) slower
```
```ruby
require 'benchmark/ips'
class Foo
def foo
123
end
end
Benchmark.ips do |x|
foo = Foo.new
x.report('Object#send') {
foo.send(:foo)
}
x.report('Object#public_send') {
foo.public_send(:foo)
}
x.compare!
end
```
=> Use Object#send in order to increase performance

lib/alba/resource.rb, test/usecases/root_key_collection_test.rb
- Close #195 
- Add fluent interface to set root key for collection
- Add class method `root_key_for_collection` in `Alba::Resources`
You can now set root key for collection using `root_key_for_collection`
```ruby
class UserResource
root_key_for_collection :users
attributes :id, :name
end
```
```ruby
@users = [OpenStruct.new(id: 1, name: "heka1024")]
UserResource.new(@users).serialize
=> Add `root_key_for_collection` in `Alba::Resource`

README.md, lib/alba/association.rb, test/usecases/many_test.rb, test/usecases/params_test.rb
Hey! This is my proposal with small enhancement for filter proc function. In rare cases it may be helpful to have an access to instance of the initial object(for example, to `User` instance in a `User <- Article` relation chain).
Please, see the tests for a synthetic example I've added there for what it may be used.
=> [Feat] Passing an initial object to proc function in associations

docs/migrate_from_jbuilder.md
While `Jbuilder.key_format!` and `Jbuilder.deep_format_keys!` aren't supported in exactly the same way, we could point users migrating from Jbuilder to consider using `transform_keys`.
=> Mention transform_keys in the Jbuilder docs

lib/alba/conditional_attribute.rb, lib/alba/resource.rb, test/usecases/conditional_attributes_test.rb
This might be good performance as well since we can now skip conditional check, but the main purpose of this change is readability.
=> [Refactor] Extract conditional_attribute into a class

lib/alba/resource.rb, test/usecases/one_test.rb
I encountered this bug but couldn't reproduce in test code.
I added some more tests for inferring resource to make sure
things still work.
=> [Fix] the bug where nesting is empty string and invalid

.rubocop.yml, README.md, lib/alba/association.rb, lib/alba/resource.rb, test/usecases/key_transform_test.rb
=> Cascade key transformation

lib/alba/nested_attribute.rb, lib/alba/resource.rb, test/usecases/nested_attribute_test.rb
Temporal implementation for nested attribute.
Let's compare it with #236 and see which is a better approach.
=> [Feat] nested attribute

README.md
...otherwise, you might have an error like I did!
```
$ rake test
rake aborted!
NoMethodError: undefined method `empty?' for nil:NilClass
/Users/trevorturk/Code/alba/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
```
=> README: add 'bundle exec' to a missing spot

CHANGELOG.md, README.md, lib/alba/resource.rb, test/alba_test.rb, test/resource_test.rb, test/usecases/nil_handler_test.rb
`as_json` returns a Hash like `serializable_hash`, but its result is similar to the result of `serialize`. In other words, `as_json` is a Hash version of `serialize`.
Since I changed the root key from String to Symbol, there's one breaking change that affects those who use Oj with `object` mode.
=> [Feat] Implement `as_json`

README.md
This PR fixes the following outdated links in README like:
```diff
- https://github.com/okuramasafumi/alba/tree/master/benchmark
+ https://github.com/okuramasafumi/alba/tree/main/benchmark
```
NOTE: I have also double-checked that all of the updated links work fine by hand. :eyes: ✅
=> Fix outdated internal links: master -> main

README.md, docs/rails.md, lib/alba/resource.rb, test/resource_test.rb
Rails automatically calls `to_json` with `render json: something`. Rails passes `options` argument to `to_json` that Alba didn't accept. This commit makes Alba to accept `options` in `to_json`. Note that `options` is dummy in Alba.
Close #250
=> [Fix] let Rails implicitly call `to_json`

CHANGELOG.md
* Add note about the default inflector no longer being set automatically
When upgrading to Alba 2.0, I ran into this breaking change unexpectedly:
```
Alba::Error: Inflector is nil. You can set inflector with `Alba.enable_inference!(with: :active_support)` for example.
```
This PR adds to the CHANGELOG to highlight the issue and suggest a fix for a typical case in Rails.
=> [Doc] Improve CHANGELOG

lib/alba.rb, lib/alba/association.rb, lib/alba/nested_attribute.rb, test/usecases/key_transform_test.rb
The cause of the bug was the usage of `Alba.assign_resource`, that evaluate given block and return the class object. So, when it's called, DSLs such as `attributes` are already evaluated. When we call `transform_keys` AFTER that call, `attributes` is assigned with empty key transformation configuration.
So I avoided this bug by not giving a block to `assign_resource` and call `transform_keys` and then call `class_eval` manually.
Fix #260
=> [Fix] key transformation now cascades multiple levels

docs/rails.md
related to #267 
just fixed missing statement `with:` before `:active_support` in the [README](https://github.com/okuramasafumi/alba/blob/main/docs/rails.md#initializer).
=> README: add 'with:' to a missing spot

lib/alba.rb, lib/alba/association.rb, lib/alba/resource.rb, test/alba_test.rb, test/dependencies/test_dependencies.rb, test/support/custom_inflector.rb, test/usecases/circular_association_test.rb, test/usecases/key_transform_test.rb, test/usecases/many_test.rb, test/usecases/nested_attribute_test.rb, test/usecases/one_test.rb, test/usecases/with_inference_test.rb
Deprecated methods are:
* `Alba.enable_inference!`
* `Alba.disable_inference!`
* `Alba.inferring`
All APIs are now united to `Alba.inflector`, so:
* Use `Alba.inflector = SomeInflector` to set inflector
* Use `Alba.inflector = nil` to disable inference
* Use `Alba.inflector` to check if inference is enabled
=> [Deprecate] inference related APIs

README.md
Some of the code examples in the README.md don't work as illustrated, or they use deprecated methods. This PR fixes as many of the fixable examples as I could find. (In a few cases, there wasn't actually an inaccuracy in the example output, but I reformatted the string to not contain `\"`.)
(I found these changes using a tool that I wrote: https://github.com/davidrunger/living_document/ . It doesn't work very smoothly, and I don't really recommend that anyone else try using that tool, but I'm just mentioning it for context.)
=> Fix various code examples and outputs in the README

CHANGELOG.md, README.md
When working on #258 I found the documentation to be a bit confusing. I tried to tidy things up a bit here with the following changes:
* Consolidate "inference" and "inference configuration" into one section
* Link to "inference configuration" when relevant
* Rename "inference" section and link it to "inference configuration"
* Prefer the word "inference" to the word "inflector" where possible
FWIW I still find the language a bit awkward. I was expecting Alba to expose a different API for configuring inference/inflection. Perhaps it's confusing because we configure the "inflector" for both "inflection" and "inference" but I'm not sure if it's worth making a big change. 
To illustrate a possible option, we could imagine changing the API from the first to the second:
```ruby …
```
=> [Doc] Tweak README to clarify inference/inflector configuration

README.md, lib/alba/conditional_attribute.rb, test/usecases/conditional_attributes_test.rb
I noticed that one of the examples in the README.md is currently not working as it claims to work.
This is the example:
```rb
class User
attr_accessor :id, :name, :email, :created_at, :updated_at
def initialize(id, name, email)
@id = id
@name = name
@email = email
end
end
class UserResource
attributes :id, :name, :email, if: proc { |user, attribute| !attribute.nil? }
end
user = User.new(1, nil, nil)
UserResource.new(user).serialize # => '{"id":1}'
```
However, the last line of that example is inaccurate.
It currently does _not_ actually return this:
```rb
UserResource.new(user).serialize # => '{"id":1}'
```
It actually returns this:
```rb
UserResource.new(user).serialize # => '{"id":1,"name":null,"email":null}'
```
With the change made in this PR, that example now …
=> Allow ConditionalAttribute with 2-arity proc to reject nil attributes

lib/alba/association.rb, test/usecases/one_test.rb
This PR adds support for using `procs` in `one` associations for selecting the `resource` serializer.
So, now will be able to use something like this:
```
class SoundtrackSerializer
one :content, resource: ->(content) { content.is_a?(Movie) ? MovieResource : TvShowResource }
end
```
=> Add support for proc resource in one polymorphic associations

README.md
Just a little fix in the `README.md` adding missing `resource` key when using proc in relationships.
=> Fix README.md adding resource key when using proc

Gemfile
It seems `inch` project is abandoned. I saw the badge was removed more than one year ago, so, I don't think the gem is still needed.
=> Remove inch gem

lib/alba/resource.rb, test/usecases/key_transform_test.rb
This is because cascade setting is not inherited.
Now the default value is true and is inherited.
Fix #299
=> Fix cascade not working with association and inheritance

Gemfile, lib/alba.rb, lib/alba/railtie.rb, test/dependencies/railties_test.rb
This is a temporary implementation of how to automatically set default inflector with Rails.
I haven't tested with user-defined inflector setting.
=> [Feat] Rails integration to set default inflector

lib/alba.rb, lib/alba/resource.rb, test/alba_test.rb, test/resource_test.rb
`Alba.symbolize_keys!` makes Alba to symbolize keys. `Alba.stringify_keys!` make Alba to stringify keys. The default is stringifying.
Close #303
=> [Feat] Add compatibility option for key

README.md, lib/alba/resource.rb, test/usecases/key_transform_test.rb
Resource name inference worked like below:
|Class name|Resource name|
| --- | --- |
| FooResource | Foo |
| FooSerializer | FooSerializer |
| FooElse | FooElse |
However we noticed that lots of users use the term `Serializer` and the current behavior is not convenient. It now works like below:
|Class name|Resource name|
| --- | --- |
| FooResource | Foo |
| FooSerializer | Foo |
| FooElse | FooElse |
It now deletes `Serializer` suffix as well.
=> [Feat] It now infers resource name from Serializer

lib/alba/nested_attribute.rb, lib/alba/resource.rb, test/usecases/params_test.rb
I like the idea of nested attributes to organize the resources but one limitant factor is that they don't inherit the params object. This felt unexpected to me as the block passed to nested_attribute looks like it runs on the same scope as the rest of the resource.
Since it looked like a small change, i decided to try to do it myself. I tried to follow previous pull requests and other parts of the code. I would be happy to make any changes you think necessary (and it would also be fine if you end up closing it) as this PR is partially an exercise in contributing to open source. :slightly_smiling_face:
=> [Feat] Gives access to params in nested_attribute

.rubocop.yml, README.md, lib/alba/resource.rb, test/usecases/object_method_and_resource_method_test.rb
#277 was closed while ago, and it's fully resolved!
=> Prefer resource method

README.md
Hello,
I hope you are doing well. I wanted to bring to your attention that I encountered some issues while attempting to copy examples from the README. It was a bit surprising to find that they didn't work as expected. Specifically, when I tried the inline layout, I encountered an ArgumentError, and I tried to find any errors I might have made on my end.
---
```ruby
layout inline: proc do
{
header: "my header",
body: serializable_hash
}
end
```
raises the following error
```
ArgumentError
tried to create Proc object without a block
```
because of different precedence of `do..end` and `{..}`. So, either
```ruby
layout inline: proc {
}
```
or
```ruby
layout(inline: proc do
end)
```
=> Update README about `layout` usage

.github/workflows/main.yml, .github/workflows/perf.yml, lib/alba/resource.rb
The unquoted 3.0 in the set of Rubies being run is truncated to 3, which results in the latest Ruby 3 to be loaded in this case (currently 3.2.2).  That's not the intended behavior.  Quoting the 3.0 ensures that the desired Ruby 3.0.x version is run for this matrix entry.
Also removed extra blank lines that were causing the lint step to fail.
=> Quote the 3.0 in GitHub action definition to avoid truncation. 

lib/alba/association.rb, lib/alba/conditional_attribute.rb, lib/alba/resource.rb, test/usecases/object_method_and_resource_method_test.rb
For example, `params` method is on every Resource class, but they're not intended to be used as attribute.
So, `attributes :params` should work when `prefer_resource_method` is on.
Fix #342 #343
=> [Fix] Resource method is those explicitly defined only

lib/alba/nested_attribute.rb, lib/alba/resource.rb, test/usecases/circular_association_test.rb
=> [Fix] Fix circular association for nested_attribute

lib/alba.rb, lib/alba/railtie.rb, test/dependencies/railties_test.rb
Close #368 
The current problem is how to test this feature. I know I can test it with a dummy app, but it seems too heavy.
=> [Feat] Rails controller integration

lib/alba.rb
They are useful by themselves and it's a preparation for TypeScript type export feature.
=> [Feat] Add `ArrayOfString` and `ArrayOfInteger` type

alba.gemspec
Hey,
with this fix, we supress the warning: 
```txt
/usr/local/bundle/gems/alba-3.2.0/lib/alba.rb:4: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
```
best regards
=> Add ostruct as gemspec dependency to be prepared for ruby 3.3.5.

lib/alba/railtie.rb, test/dependencies/railties_test.rb
https://github.com/okuramasafumi/alba/discussions/373#discussioncomment-11476049
=> [Feat] `render_serialized_json` now works with `root_key` and `meta`

alba.gemspec
I noticed that the released gem contains some unnecessary files, such as logos, benchmarking code, etc. This PR cleans it up a bit.
=> Cleanup released gem

lib/alba.rb
Ruby 3.0 introduced the `Symbol#name` method that acts as `Symbol#to_s` but returns a frozen string, we can utilize this method to reduce number of objects Alba creates during serialization.
BEFORE (no YJIT, no Oj):
```
IPS:
Comparison:
panko:      692.4 i/s
alba_with_transformation:      276.5 i/s - 2.50x  slower
alba:      240.7 i/s - 2.88x  slower
alba_inline:       75.1 i/s - 9.21x  slower
MEMORY:
Comparison:
panko:     259178 allocated
alba_with_transformation:     650141 allocated - 2.51x more
alba:     826201 allocated - 3.19x more
alba_inline:    2711921 allocated - 10.46x more
```
AFTER (no YJIT, no Oj):
```
IPS:
Comparison:
panko:      668.5 i/s
alba_with_transformation:      276.8 i/s - 2.42x  slower
alba:      264.6 i/s - 2.53x  slower
alba_inline:       74.4 i/s - 8.99x …
```
=> Use Symbol#name to minimize memory allocation

lib/alba/resource.rb, test/resource_test.rb
because we have `Serializer` alias here
https://github.com/okuramasafumi/alba/blob/d56583249521193471d27d453964c4665b876250/lib/alba/resource.rb#L547
i thought it would be cool if we can alias `serializer` as keyword argument for `resource` 😄
```ruby
class ApplicationSerializer
include Alba::Serializer
end
class CustomerSerializer < ApplicationSerializer
attributes :id, :name, :notes, :address, :contact, :updated_at
has_many :invoices, serializer: InvoiceSerializer
has_many :today_invoices, serializer: InvoiceSerializer
end
```
=> Add `serializer` keyword argument as an alias for `resource`

benchmark/collection.rb
I'm not sure why it was disabled, as [the associated PR has no justification](https://github.com/okuramasafumi/alba/pull/166). But I assume it was for speed or for more consistent results.
But Benchmark.ips takes care to run the code enough to know the margin of error.
As for speed, it actually makes the benchmark slower, because at some point allocating new pages is slower than letting the GC do its work.
Before:
```
alba        466.635 (±34.7%) i/s    (2.14 ms/i) -      2.080k in   5.014043s
alba_with_transformation    393.942 (±21.6%) i/s    (2.54 ms/i) -      1.920k in   5.165633s
alba_inline         17.251 (±23.2%) i/s   (57.97 ms/i) -     84.000 in   5.077454s
ams         32.664 (±18.4%) i/s   (30.62 ms/i) -    159.000 in   5.063782s
blueprinter        180.512 (±70.4%) i/s    (5.54 …
```
=> Don't disable GC.

lib/alba/resource.rb
While profiling the bechmark, I noticed that unsurprisingly `set_key_and_attribute_body_from` is a hotspot.
What was surprising however is that it spends almost half its time in `String#==` and `Integer#==`.
This is caused by:
```ruby
unless value == Alba::REMOVE_KEY
```
Here `value` can be a lot of different types, whereas `REMOVE_KEY` is always the same instance of `Object`.
So there is two optimizations here, first we present the call site from being megamorphic, helping YJIT optimize it.
Second we ensure the `==` implementation used is always the `Object#==` which is a simple pointer comparison.
Before:
```
ruby 3.4.1 (2024-12-25 revision 48d4efcb85) +YJIT +PRISM [arm64-darwin23]
Warming up --------------------------------------
alba    53.000 i/100ms
Calculating …
```
=> Optimize `set_key_and_attribute_body_from`

lib/alba/resource.rb, test/usecases/key_transform_test.rb
Hey
Thanks for the gem and for the regular updates!
I've been using the new `traits` feature, but it appeared `transform_keys` doesn't propagate to `trait "mytrait" do ... end` blocks. This resulted in a mixed key format:
I believe this is not an intended behavior, so I created this PR to address this.
Please share your thoughts!
=> [Feat] apply transform_keys directive for traits

README.md, lib/alba/association.rb, lib/alba/resource.rb, test/usecases/association_source_test.rb
You can specify a custom source for associations using the `source` option with a proc. The `source` proc is executed in the context of the target object and can receive `params` for dynamic behavior. This allows you to retrieve association data from methods other than the association name or access instance variables.
```ruby
class User
attr_accessor :id, :name, :metadata
def custom_profile
{profile: {email: "#{name.downcase}@example.com"}}
end
end
class UserResource
attributes :id, :name
one :profile, source: proc { custom_profile[:profile] }
one :user_metadata, source: proc { @metadata }
end
```
=> [Feat] Add source option to associations
